namespace NamiCustomers.Infrastucture.ExternalServices.SevenSoft.Dtos;
 
public class ChassisInformationByVinNumberResponse
{
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public string VinNumber { get; set; }
    public string MotorNumber { get; set; }
    public string ProductYear { get; set; }
    public string ProductMonth { get; set; }
    public string BodyColorId { get; set; }
    public string BodyColor { get; set; }
    public string InternalColorId { get; set; }
    public string InternalColor { get; set; }
    public object HarmonicColorId { get; set; }
    public string HarmonicColor { get; set; }
    public string VehicleModelId { get; set; }
    public string VehicleModelName { get; set; }
    public object VehicleId { get; set; }
    public object Vehicle { get; set; }
    public object VehicleTypeId { get; set; }
    public object VehicleType { get; set; }
    public object WarehouseBranchId { get; set; }
    public object WarehouseBranch { get; set; }
    public object WarehouseDealerId { get; set; }
    public object WarehouseDealer { get; set; }
    public object SourceWarehouseId { get; set; }
    public object SourceWarehouse { get; set; }
    public object ChassisUsageTypeId { get; set; }
    public string ChassisUsageTypeName { get; set; }
    public bool CorporateChassis { get; set; }
    public object ValidGuarantyCostCenter { get; set; }
    public object OrderingZoneId { get; set; }
    public object WarrantyCardNumber { get; set; }
    public object OriginalVinNumber { get; set; }
    public object LastKilometer { get; set; }
    public object LastClock { get; set; }
    public object LastVisitDate { get; set; }
    public object StrLastVisitDate { get; set; }
    public object LastTechnesian { get; set; }
    public object LastReceptionCode { get; set; }
    public int ProductStatusId { get; set; }
    public string ProductStatus { get; set; }
    public string FullSystem { get; set; }
    public string SelectedCountry { get; set; }
    public int SelectedTiresCount { get; set; }
    public int SelectedAxisCount { get; set; }
    public string SelectedMotorValume { get; set; }
    public string SelectedMotorKind { get; set; }
    public int SelectedCilanderCount { get; set; }
    public string SelectedSystem { get; set; }
    public object SelectedBrand { get; set; }
    public object SelectedChassisPlate { get; set; }
    public string VehicleCapacity { get; set; }
    public string SelectedVehicleDescription { get; set; }
    public string SelectedVehicleCommonName { get; set; }
    public int PDIStatusTypeId { get; set; }
    public string PDIStatusTypeName { get; set; }
    public int PercentOrAmountTypeEnum { get; set; }
    public float Discount { get; set; }
    public object DamagedDescription { get; set; }
    public bool NotAllocatable { get; set; }
    public bool DoneDestroyedProcess { get; set; }
    public object ChassisAllocationStatusId { get; set; }
    public object NumberChassisInfoDestroyedProcess { get; set; }
    public object ChassisAllocationStatusLocalizedName { get; set; }
    public float Price { get; set; }
    public object RackId { get; set; }
    public bool IsVisited { get; set; }
    public bool InActive { get; set; }
    public object ProductionDate { get; set; }
    public object StrProductionDate { get; set; }
    public object VehicleUsageTypeId { get; set; }
    public object VehicleUsageType { get; set; }
    public object BodyNumber { get; set; }
    public object ReliefSubscriptionCode { get; set; }
    public bool ChassisAllocationAutomattic { get; set; }
    public object UpholsteryMaterialId { get; set; }
    public object VehicleCommonName { get; set; }
    public object VehicleModelLocalizedName { get; set; }
    public object VehicleLocalizedName { get; set; }
    public object VehicleTypeLocalizedName { get; set; }
    public object PartSerialId { get; set; }
    public object PartId { get; set; }
    public object Serial { get; set; }
    public object ProviderId { get; set; }
    public object BrandId { get; set; }
    public DateTime? PDICahngeDate { get; set; }
    public object SecondMotorNumber { get; set; }
    public bool LicenseOfSaleFromWarehouse { get; set; }
    public DateTime CreatedOn { get; set; }
    public string StrCreatedOn { get; set; }
    public bool Inspected { get; set; }
    public DateTime VehicleModelCreatedOn { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}
