namespace NamiCustomers.Infrastucture.ExternalServices.SevenSoft.Dtos;

public class GetApplicantRegistrationReportResponse
{
    public Vehiclesale? VehicleSale { get; set; }
    public Accounting[] Accounting { get; set; }
}



public class ApplicantRegistrationRootobject
{
    public Reportdetail ReportDetail { get; set; }
    public Vehiclesale VehicleSale { get; set; }
    public Vehiclesalecontentpattern VehicleSaleContentPattern { get; set; }
    public Branchcontactinfo[] BranchContactInfo { get; set; }

    public Textofprinteddetail TextOfPrintedDetail { get; set; }
    public Signaturemodel SignatureModel { get; set; }
    public Accounting[] Accounting { get; set; }
}

public class Reportdetail
{
    public string CompanyName { get; set; }
    public string ManagerName { get; set; }
    public DateTime PrintDate { get; set; }
    public string StrPrintDate { get; set; }
    public string StrPrintTime { get; set; }
    public object PrintPersonnelName { get; set; }
    public object DocumentName { get; set; }
    public object DocumentNumber { get; set; }
    public object PayableAmountToLetters { get; set; }
    public float PayableAmount { get; set; }
    public object DealerName { get; set; }
    public object BranchName { get; set; }
    public object StartDate { get; set; }
    public object StrStartDate { get; set; }
    public object StrStartTime { get; set; }
    public object EndDate { get; set; }
    public object StrEndDate { get; set; }
    public object StrEndTime { get; set; }
    public object ReceptionControlDescription { get; set; }
    public float PrePayment { get; set; }
    public object RegisterCode { get; set; }
    public object CompanyWebSite { get; set; }
    public int DealerCode { get; set; }
    public object FiscalYear { get; set; }
    public object OnlineSaleUrl { get; set; }
    public object NationCode { get; set; }
    public object Address { get; set; }
    public object Tel { get; set; }
    public object Fax { get; set; }
    public object PostalCode { get; set; }
    public object TotalWarrantyWithTax { get; set; }
}

public class Vehiclesale
{
    public string UniqueId { get; set; }
    public object StatusIndex { get; set; }
    public int Code { get; set; }
    public int VehicleSaleCode { get; set; }
    public string? VehicleSaleNumber { get; set; }
    public int VehicleSaleCounterCode { get; set; }
    public object VehicleDimensions { get; set; }
    public string RingType { get; set; }
    public object NumberAirbags { get; set; }
    public int? BuckCapacity { get; set; }
    public string SunRoof { get; set; }
    public object PollutionStandard { get; set; }
    public string InternalColorDetailLocalizedName { get; set; }
    public string BodyColorDetailLocalizedName { get; set; }
    public object VehicleLocalizedName { get; set; }
    public string MotorValume { get; set; }
    public string MotorPower { get; set; }
    public string FuelSystem { get; set; }
    public string GearBox { get; set; }
    public string VehicleCountry { get; set; }
    public string SalePaymentTerm { get; set; }
    public bool IsFullShare { get; set; }
    public int DealerSystemCode { get; set; }
    public int BranchSystemCode { get; set; }
    public string VehiclesaleDealerNo { get; set; }
    public bool Lock { get; set; }
    public bool IsCanceled { get; set; }
    public int VehicleSaleStateId { get; set; }
    public string VehicleSaleDealerId { get; set; }
    public string VehicleSaleBranchId { get; set; }
    public object PurchaseRequestId { get; set; }
    public object PurchaseRequestDetailId { get; set; }
    public string SubscriberId { get; set; }
    public string SubscriberName { get; set; }
    public string SubscriberAddress { get; set; }
    public string SubscriberPostalCode { get; set; }
    public string SubscriberNationalCode { get; set; }
    public string SubscriberTel { get; set; }
    public string SubscriberMobile { get; set; }
    public string SalePlanId { get; set; }
    public string SaleBasketId { get; set; }
    public object SaleBasketVehicleModelId { get; set; }
    public object SaleBasketColorId { get; set; }
    public string VehicleTypeName { get; set; }
    public string VehicleName { get; set; }
    public object VehicleDescription { get; set; }
    public string VehicleModelId { get; set; }
    public string VehicleModelName { get; set; }
    public int VehicleCilanderCount { get; set; }
    public string VehicleMotorValume { get; set; }
    public object BrandId { get; set; }
    public string BrandLocalizedName { get; set; }
    public object BrandEnglishName { get; set; }
    public string BodyColorDetailId { get; set; }
    public string BodyColorDetail { get; set; }
    public string InternalColorDetailId { get; set; }
    public string InternalColorDetail { get; set; }
    public object Accessorie { get; set; }
    public object HarmonicColorDetailId { get; set; }
    public string HarmonicColorDetail { get; set; }
    public object ChassisInfoId { get; set; }
    public string SaleBasketInventoryControlId { get; set; }
    public string SalePlanCode { get; set; }
    public string SalePlanName { get; set; }
    public string SalePlanGroup { get; set; }
    public string SalePlanSecondaryType { get; set; }
    public string SalePlanCategory { get; set; }
    public string SaleBasketNo { get; set; }
    public string SaleBasketName { get; set; }
    public string SaleBasketType { get; set; }
    public string SaleBasketStartDate { get; set; }
    public string SaleBasketEndDate { get; set; }
    public string SalePlanConditionId { get; set; }
    public int SalePaymentTermId { get; set; }
    public object VehicleModelSalePriceId { get; set; }
    public float VehicleSalePrice { get; set; }
    public string StrVehicleSalePrice { get; set; }
    public float VehicleSaleCooperationProfitPercent { get; set; }
    public string StrVehicleSaleCooperationProfitPercent { get; set; }
    public float VehicleSaleDiscountAmount { get; set; }
    public string StrVehicleSaleDiscountAmount { get; set; }
    public float VehicleSaleCancellationProfitPercent { get; set; }
    public string StrVehicleSaleCancellationProfitPercent { get; set; }
    public float VehicleSaleDelayProfitPercent { get; set; }
    public string StrVehicleSaleDelayProfitPercent { get; set; }
    public float VehicleSaleWagePercent { get; set; }
    public string StrVehicleSaleWagePercent { get; set; }
    public string VehicleUsageTypeId { get; set; }
    public string VehicleUsageTypeName { get; set; }
    public string FiscalYearId { get; set; }
    public string Description { get; set; }
    public int RequestCustomer { get; set; }
    public bool Invoiced { get; set; }
    public object InvoiceDate { get; set; }
    public string StartDate { get; set; }
    public object PreInvoicedDate { get; set; }
    public object PreInvoicedDateStr { get; set; }
    public object PreInvoicedExpireDateStr { get; set; }
    public object DealerPreInvoiceNumber { get; set; }
    public object BranchPreInvoiceNumber { get; set; }
    public object PreInvoiceNumberByYear { get; set; }
    public object PreInvoicedExpireDate { get; set; }
    public int PreInvoiceNumber { get; set; }
    public object DealerInvoiceNumber { get; set; }
    public object BranchInvoiceNumber { get; set; }
    public object DealerCollectiveInvoiceNumber { get; set; }
    public object BranchCollectiveInvoiceNumber { get; set; }
    public object DealerCollectiveInvoiceNumberByYear { get; set; }
    public object BranchCollectiveInvoiceNumberByYear { get; set; }
    public int PrintCountInvoice { get; set; }
    public object TotalAmount { get; set; }
    public object DiscountValue { get; set; }
    public object DiscountFee { get; set; }
    public object DiscountPercent { get; set; }
    public object Tax { get; set; }
    public object Toll { get; set; }
    public object EndAmount { get; set; }
    public object InvoiceFiscalYearId { get; set; }
    public bool IncludesTax { get; set; }
    public object CustomerDeliveryFullName { get; set; }
    public object DeliveryPersonnelId { get; set; }
    public object DeliveryKilometer { get; set; }
    public object DeliveryDate { get; set; }
    public object DeliveryTime { get; set; }
    public object StrDeliveryDate { get; set; }
    public int PrintCountDelivery { get; set; }
    public object DeliveryDescription { get; set; }
    public object DeliveryPersonnelSignatureId { get; set; }
    public object DeliveryPersonnelSignature { get; set; }
    public string VehiclesaleDealer { get; set; }
    public string VehiclesaleBrach { get; set; }
    public object SelectedChassisChassisInfoId { get; set; }
    public string? SelectedChassisVinNumber { get; set; }
    public string? SelectedChassisMotorNo { get; set; }
    public object SelectedChassisSecondMotorNo { get; set; }
    public string SelectedChassisBodyColorDetailId { get; set; }
    public string SelectedChassisBodyColorDetailName { get; set; }
    public string SelectedChassisInternalColorDetailId { get; set; }
    public string SelectedChassisInternalColorDetailName { get; set; }
    public object SelectedChassisHarmonicColorDetailId { get; set; }
    public string SelectedChassisHarmonicColorDetailName { get; set; }
    public object SourceWarehouse { get; set; }
    public object SelectedChassisVehicleModelId { get; set; }
    public object SelectedChassisVehicleModelName { get; set; }
    public string SelectedChassisChassisUsageTypeName { get; set; }
    public int AreaCategoryId { get; set; }
    public string AreaCategory { get; set; }
    public string SellerPersonnelId { get; set; }
    public Vehiclesalesubscriber[] VehicleSaleSubscribers { get; set; }
    public object StrVehicleSaleSubscriber { get; set; }
    public object CardexDate { get; set; }
    public string SaleType { get; set; }
    public DateTime RegDate { get; set; }
    public string HeaderSalerType { get; set; }
    public string HeaderCustomerType { get; set; }
    public string SalePaymentTermName { get; set; }
    public string MainSubscriberId { get; set; }
    public int SaleCategoryId { get; set; }
    public string SaleCategory { get; set; }
    public object UsedContractTypeId { get; set; }
    public object UsedContractType { get; set; }
    public object UsedContractTypeCode { get; set; }
    public object UsedVehicleContractId { get; set; }
    public object UsedVehicleContract { get; set; }
    public object ConfirmedDate { get; set; }
    public object StrConfirmedDate { get; set; }
    public DateTime SalePlanDate { get; set; }
    public string StrSalePlanDate { get; set; }
    public bool Status { get; set; }
    public object StatusDescriptoin { get; set; }
    public int VehicleSaleTrackingStepId { get; set; }
    public string VehicleSaleTrackingDescription { get; set; }
    public string VehicleSaleProductYear { get; set; }
    public int VehicleSaleUnCertainPrice { get; set; }
    public object UncertainCurrentSalePrice { get; set; }
    public object VehicleSaleEstimatedInvitationDate { get; set; }
    public object VehicleSaleEstimatedDeliverDate { get; set; }
    public string SaleBasketVehicleModelProductYear { get; set; }
    public bool IsFundCompleted { get; set; }
    public bool NoPaymentsRegistered { get; set; }
    public object VehicleSaleTrackingLastDescriptoinBeforeCanceling { get; set; }
    public object VehicleSaleTrackingLastStepIdBeforeCancelingId { get; set; }
    public object BankAccountNumberId { get; set; }
    public object BankAccountCardNumber { get; set; }
    public object BankAccountCardIRNumber { get; set; }
    public string VehicleSaleFollowupDealerId { get; set; }
    public string VehicleSaleDeliveryDealerId { get; set; }
    public string VehicleSaleFollowupBranchId { get; set; }
    public string VehicleSaleDeliveryBranchId { get; set; }
    public object Accessories { get; set; }
    public object AccessoriesSelectedList { get; set; }
    public object VehicleSaleGifts { get; set; }
    public object VehicleSaleGiftsSelectedList { get; set; }
    public object Documents { get; set; }
    public object DocumentsSelectedList { get; set; }
    public object VehicleTypeId { get; set; }
    public object VehicleDeliverICheckListRefrenceId { get; set; }
    public object VehicleTransportDeclarationChassisId { get; set; }
    public object VehicleSaleId { get; set; }
    public object ChassisDeliverCheckListDescription { get; set; }
    public object StrChassisDeliverCheckListPositions { get; set; }
    public object ChassisDeliverCheckListPositions { get; set; }
    public string ChassisDeliverCheckListUniqueId { get; set; }
    public bool VehicleSaleCheckTax { get; set; }
    public string ReportSubject { get; set; }
    public string FirstContractTitle { get; set; }
    public string SecondContractTitle { get; set; }
    public object ReferenceUnitId { get; set; }
    public float ProposalPriceVehiclePrice { get; set; }
    public float ProposalPriceVehiclePriceTax { get; set; }
    public int ProposalPriceDeliverDayCount { get; set; }
    public string ProposalPriceVehicleSaleDealer { get; set; }
    public string ProposalPriceVehicleSaleBranch { get; set; }
    public object ProposalPriceVehiclePriceWord { get; set; }
    public string ProposalPriceVehicleSaleDeliveryDealer { get; set; }
    public string ProposalPriceVehicleSaleDeliveryBranch { get; set; }
    public string ProposalPriceVehicleCapacity { get; set; }
    public bool IsNotEditable { get; set; }
    public object OptionListDetailCheckBoxList { get; set; }
    public object OptionListDetail { get; set; }
    public object StartGuarantyDate { get; set; }
    public object StartGuarantyDateDescription { get; set; }
    public object SaleSessionContnt { get; set; }
    public float PayableAmount { get; set; }
    public object FatherName { get; set; }
    public object IdNumber { get; set; }
    public object EndDate { get; set; }
    public object MainEndDate { get; set; }
    public float SumDebitFee { get; set; }
    public float RemainingAmount { get; set; }
    public float Prepayment { get; set; }
    public float SumPrePaymentDebitFee { get; set; }
    public float FirstPrePaymentDebitFee { get; set; }
    public bool SalePlanInActive { get; set; }
    public float SalePlanFinancialFactorGroupLateProfitAmount { get; set; }
    public object VehicleId { get; set; }
    public object City { get; set; }
    public object SubCountry { get; set; }
    public object Address { get; set; }
    public object Tel { get; set; }
    public object Mobile { get; set; }
    public object DealerName { get; set; }
    public object BranchName { get; set; }
    public object SaleBasket { get; set; }
    public object VehicleUsageType { get; set; }
    public bool IsVehicleModelChangePermitted { get; set; }
    public bool IsCancelationPermitted { get; set; }
    public bool IsOwnerShipTransferPermitted { get; set; }
    public bool IsChangeSalePlanPermitted { get; set; }
    public bool IsVehicleModelColorChangePermitted { get; set; }
    public object Birthdate { get; set; }
    public object StrBirthdate { get; set; }
    public object StartInvitationDate { get; set; }
    public object StrStartInvitationDate { get; set; }
    public object EndInvitationDate { get; set; }
    public object StrEndInvitationDate { get; set; }
    public object StartDeliverDate { get; set; }
    public object StrStartDeliverDate { get; set; }
    public object EndDeliverDate { get; set; }
    public object StrEndDeliverDate { get; set; }
    public object ReliefSubscriptionCode { get; set; }
    public object InvoiceNumber { get; set; }
    public object InvoiceNumberByYear { get; set; }
    public object VehicleSaleGroupId { get; set; }
    public string FirstColorPriorityId { get; set; }
    public string SecondColorPriorityId { get; set; }
    public string ThirdColorPriorityId { get; set; }
    public float OptionPrice { get; set; }
    public object FirstColorPriority { get; set; }
    public object SecondColorPriority { get; set; }
    public object ThirdColorPriority { get; set; }
    public object SaleSelectionItemListColorPriorityId { get; set; }
    public object SalePlanVehicleModelId { get; set; }
    public string VehicleCommonName { get; set; }
    public object UsedVehicleContractIntermediationId { get; set; }
    public string UsedSelectedChassisVehicleModelName { get; set; }
    public string UsedVehicleSaleProductYear { get; set; }
    public string UsedSelectedChassisBodyColorDetailName { get; set; }
    public string UsedSelectedChassisInternalColorDetailName { get; set; }
    public string UsedSelectedChassisHarmonicColorDetailName { get; set; }
    public string UsedVehicleContractContractNumber { get; set; }
    public float SumRemainDebitFee { get; set; }
    public float SumPaymentDebitFee { get; set; }
    public object ChassisUsageTypeId { get; set; }
    public object ChassisUsageTypeName { get; set; }
    public object TotalProposalPriceVehiclePrice { get; set; }
    public string ExpireDateStrForShetabrun { get; set; }
    public int SalePlanFundsCompletionDays { get; set; }
    public int SalePlanDeliverDaysAfterFundsCompletion { get; set; }
    public bool ShowVehicleSaleColorPriorities { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class Vehiclesalesubscriber
{
    public string UniqueId { get; set; }
    public int Code { get; set; }
    public object PurchaseRequestId { get; set; }
    public string VehicleSaleId { get; set; }
    public string SubscriberId { get; set; }
    public object SubscriberName { get; set; }
    public float ShareCount { get; set; }
    public bool InActive { get; set; }
    public object Description { get; set; }
    public object VehicleSaleOwnerShipTransferLicenseId { get; set; }
    public object SubscriberMobile { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class Vehiclesalecontentpattern
{
    public string UniqueId { get; set; }
    public int Code { get; set; }
    public string VehicleSaleId { get; set; }
    public string VehicleSale { get; set; }
    public string SalePlanContentPatternId { get; set; }
    public string SalePlanContentPattern { get; set; }
    public string SaleContentPatternPriorityId { get; set; }
    public string SaleContentPatternPriority { get; set; }
    public string SaleContentPatternId { get; set; }
    public string SaleContentPattern { get; set; }
    public string SaleContentId { get; set; }
    public string SaleContent { get; set; }
    public string SaleContentTitle { get; set; }
    public string VehicleSaleContentPatternContentBody { get; set; }
    public string VehicleSaleContentPatternContentDate { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class Textofprinteddetail
{
    public string UniqueId { get; set; }
    public int Code { get; set; }
    public object ReceptionFactorDescription { get; set; }
    public object SecondReceptionFactorDescription { get; set; }
    public object ThirdReceptionFactorDescription { get; set; }
    public object ClaimFactorDescription { get; set; }
    public object ClaimDebtExitFactorDescription { get; set; }
    public object PartSaleFactorDescription { get; set; }
    public object ReturnFromInvoiceFactorDescription { get; set; }
    public object SatisfactionFactorDescription { get; set; }
    public object RepairCardDescription { get; set; }
    public object VeicleSaleDescription { get; set; }
    public object ReliefDescription { get; set; }
    public object WorkShopContractDescription { get; set; }
    public object GuarantySaleDescription { get; set; }
    public object DeliveryReceiptDescription { get; set; }
    public object RepairHallCardDescription { get; set; }
}

public class Signaturemodel
{
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public int ReportId { get; set; }
    public object Report { get; set; }
    public object FirstSignatoryTitle { get; set; }
    public object FirstSignatoryPersonnelId { get; set; }
    public object FirstSignatoryPersonnel { get; set; }
    public object SecondSignatoryTitle { get; set; }
    public object SecondSignatoryPersonnelId { get; set; }
    public object SecondSignatoryPersonnel { get; set; }
    public object ThirdSignatoryTitle { get; set; }
    public object ThirdSignatoryPersonnelId { get; set; }
    public object ThirdSignatoryPersonnel { get; set; }
    public object DealerId { get; set; }
    public object DealerName { get; set; }
    public object DealerNo { get; set; }
    public object BranchId { get; set; }
    public object BranchName { get; set; }
    public object BranchNo { get; set; }
    public object Description { get; set; }
    public string FirstSignatureUrl { get; set; }
    public string SecondSignatureUrl { get; set; }
    public string ThirdSignatureUrl { get; set; }
    public object SignatureCustomerUrl { get; set; }
    public object AreaCategoryId { get; set; }
    public object AreaCategoryName { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class Branchcontactinfo
{
    public string UniqueId { get; set; }
    public int Code { get; set; }
    public string BranchId { get; set; }
    public string BranchName { get; set; }
    public string BranchNameWithoutDealerName { get; set; }
    public string BranchNo { get; set; }
    public object PersonnelCode { get; set; }
    public string DealerCityLocalizedName { get; set; }
    public string DealerSubCountryLocalizedName { get; set; }
    public string DealerEconomicCode { get; set; }
    public string CentralDealerEconomicCode { get; set; }
    public object ManagerMobile { get; set; }
    public object ManagerPhone { get; set; }
    public object ManagerFax { get; set; }
    public object ManagerEmail { get; set; }
    public object ManagerAddress { get; set; }
    public object RepairShopMobileNumber { get; set; }
    public object RepairShopPhoneNumber { get; set; }
    public object RepairShopFax { get; set; }
    public object RepairShopEmail { get; set; }
    public object RepairShopAddress { get; set; }
    public object RepairShopPostalCode { get; set; }
    public object RegistrationNumber { get; set; }
    public object ExhibitionMobileNumber { get; set; }
    public object ExhibitionPhoneNumber { get; set; }
    public object ExhibitionFax { get; set; }
    public object ExhibitionEmail { get; set; }
    public object ExhibitionAddress { get; set; }
    public object ExhibitionPostalCode { get; set; }
    public object IsqiPersonName { get; set; }
    public object DealerGrade { get; set; }
    public object NationalId { get; set; }
    public string DealerNo { get; set; }
    public string DealerName { get; set; }
    public object PersonnelLocalizedName { get; set; }
    public string ManagerName { get; set; }
    public string BranchManagerName { get; set; }
    public object ManagerDescription { get; set; }
    public bool IsCentralBranch { get; set; }
    public bool IsCentralDealer { get; set; }
    public string Branch_Name { get; set; }
    public object TradingSystemRoleCode { get; set; }
    public string DealerNationalCode { get; set; }
    public string EconomicCodeFroBranch { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}



public class Accounting
{
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public string DealerId { get; set; }
    public string DealerNo { get; set; }
    public string Dealer { get; set; }
    public string BranchId { get; set; }
    public string BranchNo { get; set; }
    public string Branch { get; set; }
    public string SubscriberId { get; set; }
    public string Subscriber { get; set; }
    public string SubscriberName { get; set; }
    public string SubscriberNationalCode { get; set; }
    public object ChassisInfoId { get; set; }
    public string VinNumber { get; set; }
    public object VehicleName { get; set; }
    public object VehicleTypeName { get; set; }
    public object ContractNo { get; set; }
    public int BussinesTypeId { get; set; }
    public string BussinesType { get; set; }
    public string RelatedId { get; set; }
    public object RelatedName { get; set; }
    public string RelatedCode { get; set; }
    public string AccountingTypeId { get; set; }
    public string AccountingType { get; set; }
    public string PaymentTypeId { get; set; }
    public string PaymentType { get; set; }
    public int PaymentEnum { get; set; }
    public string FundId { get; set; }
    public string Fund { get; set; }
    public DateTime Date { get; set; }
    public string strDate { get; set; }
    public string strTime { get; set; }
    public object CreatedOnDate { get; set; }
    public string strCreatedOnDate { get; set; }
    public string strCreatedOnTime { get; set; }
    public float CreditFee { get; set; }
    public float DebitFee { get; set; }
    public object DebitFeeWord { get; set; }
    public float AccountingFee { get; set; }
    public string AccountingFeeAsString => AccountingFee.ToString("000,0.");
    public string AccountingFeeAsTomanString => (AccountingFee / 10).ToString("000,0.");
    public string FollowUpCode { get; set; }
    public string DesctinationBankAccountNumberId { get; set; }
    public string DesctinationBankAccountNumber { get; set; }
    public string DesctinationBankAccountNumberWithoutName { get; set; }
    public object CardNumber { get; set; }
    public string IRNumber { get; set; }
    public string DestinationBankAccountName { get; set; }
    public string FiscalYearId { get; set; }
    public string FiscalYear { get; set; }
    public object ChequeTypeId { get; set; }
    public string ChequeType { get; set; }
    public int ChequeTypeEnum { get; set; }
    public object ChequeStatusId { get; set; }
    public string ChequeStatus { get; set; }
    public object ChequeDate { get; set; }
    public object strChequeDate { get; set; }
    public object ChequeInfo { get; set; }
    public object ChequeOwnerFullName { get; set; }
    public object ChequeOwnerAddress { get; set; }
    public object OwnerBankId { get; set; }
    public string OwnerBank { get; set; }
    public object OwnerBankBranchId { get; set; }
    public object OwnerBankBranch { get; set; }
    public object OwnerAccountNumber { get; set; }
    public object Description { get; set; }
    public object POSDeviceId { get; set; }
    public object CreditDetailId { get; set; }
    public object Credit { get; set; }
    public bool FirstStateApproved { get; set; }
    public bool FirstStateNotApproved { get; set; }
    public string FirstStateUserId { get; set; }
    public DateTime FirstStateDate { get; set; }
    public string StrFirstStateDate { get; set; }
    public object FirstStateDescription { get; set; }
    public bool SecondStateApproved { get; set; }
    public bool SecondStateNotApproved { get; set; }
    public string SecondStateUserId { get; set; }
    public DateTime SecondStateDate { get; set; }
    public string StrSecondStateDate { get; set; }
    public object SecondStateDescription { get; set; }
    public bool ThirdStateApproved { get; set; }
    public bool ThirdStateNotApproved { get; set; }
    public string ThirdStateUserId { get; set; }
    public DateTime ThirdStateDate { get; set; }
    public string StrThirdStateDate { get; set; }
    public object ThirdStateDescription { get; set; }
    public int StateOrderId { get; set; }
    public string StateOrder { get; set; }
    public object LastDraftResultCode { get; set; }
    public bool SubscriberIsLegal { get; set; }
    public object SubscriberNationalCodeOrNationalId { get; set; }
    public bool Lock { get; set; }
    public string RowVersion { get; set; }
    public bool IsNotEditable { get; set; }
    public object SelectedState { get; set; }
    public object StatusIndex { get; set; }
    public bool Canceled { get; set; }
    public bool Approved { get; set; }
    public int FirstStateAccountingStatusId { get; set; }
    public string FirstStateAccountingStatus { get; set; }
    public int SecondStateAccountingStatusId { get; set; }
    public string SecondStateAccountingStatus { get; set; }
    public int ThirdStateAccountingStatusId { get; set; }
    public string ThirdStateAccountingStatus { get; set; }
    public string LatestStatus { get; set; }
    public object VehicleSaleDate { get; set; }

    public int SalePaymentKindId { get; set; }
    public string SalePaymentKind { get; set; }
    public bool IsUsedVehicleSale { get; set; }
    public object ReceiverUser { get; set; }
    public string SubscriberMobile { get; set; }
    public object LCDate { get; set; }
    public object strLCDate { get; set; }
    public float SumPrePayment { get; set; }
    public float CalculatedEndFee { get; set; }
    public float CalculatedTaxAndToll { get; set; }
    public float CalculatedSumTaxAndTollEndFee { get; set; }
    public float CalculatedFinallEndFee { get; set; }
    public object CalculatedFinallEndFeeWord { get; set; }
    public int VehicleSaleCode { get; set; }
    public string? VehicleSaleNumber { get; set; }
    public string VehicleModel { get; set; }
    public DateTime VehiclesaleDate { get; set; }
    public string StrVehiclesaleDate { get; set; }
    public string StrVehiclesaleTime { get; set; }
    public int SalePaymentKindEnumCode { get; set; }
    public object BankBranchId { get; set; }
    public bool AccountingLink { get; set; }
    public object AccountingLinkUrl { get; set; }
    public object LeasingCompanyId { get; set; }
    public string LeasingCompany { get; set; }
    public object StockOfNumber { get; set; }
    public int Gender { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}
