

namespace NamiCustomers.Infrastucture.ExternalServices.SevenSoft.Dtos;



public class GetReceptionsInformationByVinNumberResponse
{
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public int DealerSystemCode { get; set; }
    public string ReceptionCode { get; set; }
    public object RelatedCode { get; set; }
    public object RelatedName { get; set; }
    public int ReceptionBranchDailyCode { get; set; }
    public int BranchSystemCode { get; set; }
    public object Deposit { get; set; }
    public string SubscriberChassisAllocationId { get; set; }
    public string SubscriberId { get; set; }
    public object VehicleModelId { get; set; }
    public object UserAssignmentId { get; set; }
    public object ChassisInfoId { get; set; }
    public object ChassisUsageTypeLocalizedName { get; set; }
    public object SubscriberLogId { get; set; }
    public string SubscriberName { get; set; }
    public object SubscriberFullName { get; set; }
    public object WorkTell { get; set; }
    public object WorkRoomAddress { get; set; }
    public string SubscriberChassisNo { get; set; }
    public object ParticipationCode { get; set; }
    public object OriginalVinNumber { get; set; }
    public string ChassisPlate { get; set; }
    public object SubscriberPelakNo { get; set; }
    public bool SubscriberWithoutPlate { get; set; }
    public string SubscriberMotorNo { get; set; }
    public string SubscriberVehicleModel { get; set; }
    public string SubscriberVehicleColor { get; set; }
    public bool SubscriberIsLegal { get; set; }
    public string SubscriberNationalCodeOrNationalId { get; set; }
    public string DealerId { get; set; }
    public object ReferenceDealerId { get; set; }
    public object ReferenceDealerName { get; set; }
    public object ReferenceBranchName { get; set; }
    public object ReferenceBranchId { get; set; }
    public string DealerNo { get; set; }
    public string DealerName { get; set; }
    public string BranchName { get; set; }
    public string BranchId { get; set; }
    public object BranchEditLogId { get; set; }
    public string BranchNo { get; set; }
    public DateTime RecDate { get; set; }
    public string StrRecDate { get; set; }
    public string StrRecTime { get; set; }
    public int RecKilometer { get; set; }
    public int RecClock { get; set; }
    public object Description { get; set; }
    public string RepairAdviserId { get; set; }
    public string RepairAdviserName { get; set; }
    public object CashierId { get; set; }
    public string CashierName { get; set; }
    public bool QcFlag { get; set; }
    public string CustomerName { get; set; }
    public object InternalIdentificationNumber { get; set; }
    public string CustomerMobile { get; set; }
    public object CustomerEmail { get; set; }
    public string CustomerNationalCode { get; set; }
    public string CustomerAddress { get; set; }
    public object StrEstimatedDaysToDeliver { get; set; }
    public object TotalWarrantyAmount { get; set; }
    public float EstimatedAmount { get; set; }
    public DateTime EstimatedDeliver { get; set; }
    public string StrEstimatedDeliverDate { get; set; }
    public string StrEstimatedDeliverTime { get; set; }
    public object FirstCreatedUserEstimatedDeliver { get; set; }
    public object FirstCreatedEstimatedDeliverDate { get; set; }
    public object StrFirstCreatedEstimatedDeliverDate { get; set; }
    public object StrFirstCreatedEstimatedDeliverTime { get; set; }
    public object ReliefReceptionId { get; set; }
    public string ReliefReceptionDealerSystemCode { get; set; }
    public object CarwashStartDate { get; set; }
    public string StrCarwashStartDate { get; set; }
    public object CarwashStartTime { get; set; }
    public object CarwashEndDate { get; set; }
    public string StrCarwashEndDate { get; set; }
    public object CarwashEndTime { get; set; }
    public object DeliveryDate { get; set; }
    public string StrDeliveryDate { get; set; }
    public string StrDeliveryTime { get; set; }
    public int DeliveryKilometer { get; set; }
    public int DeliveryClock { get; set; }
    public bool CheckForOwnerPart { get; set; }
    public bool CheckForOwnerStatements { get; set; }
    public int DealerCollectiveInvoiceNumber { get; set; }
    public int BranchCollectiveInvoiceNumber { get; set; }
    public int DealerCollectiveInvoiceNumberByYear { get; set; }
    public int BranchCollectiveInvoiceNumberByYear { get; set; }
    public int DealerInvoiceNumber { get; set; }
    public int BranchInvoiceNumber { get; set; }
    public DateTime InvoiceDate { get; set; }
    public string StrInvoiceDate { get; set; }
    public string StrInvoiceTime { get; set; }
    public int DealerPreInvoiceNumber { get; set; }
    public int BranchPreInvoiceNumber { get; set; }
    public DateTime PreInvoiceDate { get; set; }
    public string StrPreInvoiceDate { get; set; }
    public string StrPreInvoiceTime { get; set; }
    public int FuelStatusId { get; set; }
    public int BatteryStatusId { get; set; }
    public string FuelStatusLocalizedName { get; set; }
    public string BatteryStatusLocalizedName { get; set; }
    public float TotalAmount { get; set; }
    public float DiscountValue { get; set; }
    public float DiscountFee { get; set; }
    public float DiscountPercent { get; set; }
    public float Tax { get; set; }
    public object InServicesTax { get; set; }
    public object OutServicesTax { get; set; }
    public object PartsTax { get; set; }
    public float Toll { get; set; }
    public object InServicesToll { get; set; }
    public object OutServicesToll { get; set; }
    public object PartsToll { get; set; }
    public float EndAmount { get; set; }
    public float ParkingAmount { get; set; }
    public int ParkingDay { get; set; }
    public float StopPenaltyAmount { get; set; }
    public bool FinalPayment { get; set; }
    public bool Cancellation { get; set; }
    public bool Invoiced { get; set; }
    public object FiscalYearId { get; set; }
    public object FiscalYear { get; set; }
    public int PrintCountPreInvoice { get; set; }
    public int PrintCountInvoice { get; set; }
    public int PrintCountRepairCard { get; set; }
    public int ReceptionStateOrderId { get; set; }
    public string ReceptionStateOrder { get; set; }
    public string RowVersion { get; set; }
    public string ReceptionType { get; set; }
    public object KilometerModificationDescription { get; set; }
    public string ReceptionStatus { get; set; }
    public string DealerBranchNo { get; set; }
    public string VehicleFullName { get; set; }
    public string WarrantyStatus { get; set; }
    public object LastDraftResultCode { get; set; }
    public float PartAmount { get; set; }
    public float InServiceAmount { get; set; }
    public float OutServiceAmount { get; set; }
    public string ReceptionControlDescription { get; set; }
    public DateTime ReceptionControlDate { get; set; }
    public string StrReceptionControlDate { get; set; }
    public string StrReceptionControlTime { get; set; }
    public object WareHouseId { get; set; }
    public object ReceptionVehicleStatusGearBox { get; set; }
    public object OnlinePersonnel { get; set; }
    public object ReceptionCount { get; set; }
    public object QualityControlStartDate { get; set; }
    public string StrQualityControlStartDate { get; set; }
    public string StrQualityControlStartTime { get; set; }
    public object QualityControlEndDate { get; set; }
    public string StrQualityControlEndDate { get; set; }
    public string StrQualityControlEndTime { get; set; }
    public object ReceptionVehicleModelName { get; set; }
    public object BookingDate { get; set; }
    public string StrBookingDate { get; set; }
    public object BookingCode { get; set; }
    public object BookingKilometer { get; set; }
    public int ReceptionLicenseBranchSyastemCode { get; set; }
    public object[] ReceptionAccessoriesList { get; set; }
    public object[] ReceptionControlList { get; set; }
    public object[] ReceptionCustomerStatementsList { get; set; }
    public object[] ReceptionDashboardSymbolList { get; set; }
    public object[] ReceptionEstimatedList { get; set; }
    public object[] ReceptionInServicesList { get; set; }
    public object[] ReceptionOutServicesList { get; set; }
    public object[] ReceptionPartsOrderList { get; set; }
    public object[] ReceptionPartsList { get; set; }
    public object[] ReceptionPositionList { get; set; }
    public object[] ReceptionQualityControlList { get; set; }
    public object[] ReceptionRoadTestList { get; set; }
    public object[] ReceptionSuspensionList { get; set; }
    public object[] ReceptionTypeList { get; set; }
    public object[] ReceptionWorkShopContractList { get; set; }
    public int AreaCategoryId { get; set; }
    public object ReceptionTaskApproveDescription { get; set; }
    public object ReceptionTaskApprovedUserId { get; set; }
    public object ReceptionTaskApprovedUser { get; set; }
    public object ReceptionTaskApprovedDate { get; set; }
    public object StrReceptionTaskApprovedDate { get; set; }
    public object ReceptionCustomerSignatureId { get; set; }
    public object ReceptionFinancialCustomerSignatureId { get; set; }
    public object RepairHall { get; set; }
    public object ServerGroup { get; set; }
    public object ReceptionTimeInterval { get; set; }
    public DateTime ChassisGuaranteeRegisterDate { get; set; }
    public string StrChassisGuaranteeRegisterDate { get; set; }
    public string BrandName { get; set; }
    public object DealerEconomicCode { get; set; }
    public string DealerPostalCode { get; set; }
    public string DealerAddress { get; set; }
    public string DealerPhone { get; set; }
    public object[] ReceptionTypes { get; set; }
    public string StrReceptionTypes { get; set; }
    public int ReceptionListLastKilometer { get; set; }
    public object ReceptionInvoiceUrl { get; set; }
    public object ReceptionRepairCardUrl { get; set; }
    public object ReceptionStatusPreviewUrl { get; set; }
    public object ServiceId { get; set; }
    public object ServiceCode { get; set; }
    public object PartId { get; set; }
    public object PartNo { get; set; }
    public object PartSerial { get; set; }
    public object OldProviderName { get; set; }
    public object OldPartName { get; set; }
    public bool SendDocumentsOfBuyTransactions { get; set; }
    public int ReceptionControlCount { get; set; }
    public object VehicleTypeLocalizedName { get; set; }
    public object BrandLocalizedName { get; set; }
    public object WarehouseLocalizedName { get; set; }
    public object VehicleTypeVehicleName { get; set; }
    public string ProductYear { get; set; }
    public int DealerCode { get; set; }
    public object WeekDayStartAndEndTime { get; set; }
    public object ThursdayStartAndEndTime { get; set; }
    public object HolidayStartAndEndTime { get; set; }
    public object CurrentDay { get; set; }
    public string AbreviatedName { get; set; }
    public float AccountingOnlineCredit { get; set; }
    public object OnlineCredit { get; set; }
    public object Credit { get; set; }
    public object ProductionDate { get; set; }
    public string StrProductionDate { get; set; }
    public string VehicleTypeName { get; set; }
    public object VehicleSaleDeliveryDate { get; set; }
    public string StrVehicleSaleDeliveryDate { get; set; }
    public object IncludesTax { get; set; }
    public bool ReceptionListIsClaimAccountSettlement { get; set; }
    public object ReceptionVehicleAbreviatedName { get; set; }
    public bool ReceptionListActiveClaimAccountSettlement { get; set; }
    public object ReceptionListClaimAccountSettlement { get; set; }
    public bool DeliverFailurePartToCustomer { get; set; }
    public object VehicleTypeId { get; set; }
    public object ReceptionListBranchGrade { get; set; }
    public object NoticeDescription { get; set; }
    public object ReceptionVehicleName { get; set; }
    public object SubscriberTel { get; set; }
    public bool IsDelivered { get; set; }
    public string SubscriberBodyNumber { get; set; }
    public int Gender { get; set; }
    public string EstimatedDeliverTime { get; set; }
    public object ReceptionCustomerSignature { get; set; }
    public bool ReceptionEstimatedHasCustomersSignature { get; set; }
    public object NationalCodOrNationalId { get; set; }
    public object EconomicCode { get; set; }
    public object GuarantyTypeInReception { get; set; }
    public bool ReceptionByReceptionApp { get; set; }
    public int TotalCount { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}
