using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NamiCustomers.Infrastucture.ExternalServices.SevenSoft.Dtos;


public class ReceptionsInformationByReceptionIDResponse
{
    public SubscriberOfSevenResponse subscriber { get; set; }
    public WarrantyOfSevenResponse warranty { get; set; }
    public DealerOfSevenResponse Dealer { get; set; }
    public PartandservicelistOfSevenResponse[] PartAndServiceList { get; set; }
    public PartandservicelistbycostcenterOfSevenResponse[] PartAndServiceListByCostCenter { get; set; }
    public ReceptionOfSevenResponse Reception { get; set; }
    public ReportdetailOfSevenResponse ReportDetail { get; set; }
    public SignaturemodelOfSevenResponse SignatureModel { get; set; }
    public TextofprinteddetailOfSevenResponse TextOfPrintedDetail { get; set; }
}

public class SubscriberOfSevenResponse
{
    public object Index { get; set; }
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public object FirstName { get; set; }
    public object LastName { get; set; }
    public string FullName { get; set; }
    public string FatherName { get; set; }
    public bool IsForeignNational { get; set; }
    public string NationalCode { get; set; }
    public string RegistrationNumber { get; set; }
    public string NationalId { get; set; }
    public object PostalCode { get; set; }
    public object SubCountryLocalizedName { get; set; }
    public object CityLocalizedName { get; set; }
    public string Address { get; set; }
    public string LegalAddress { get; set; }
    public string HomeAddress { get; set; }
    public string WorkAddress { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
    public object Fax { get; set; }
    public string IdNumber { get; set; }
    public int Gender { get; set; }
    public object BirthDate { get; set; }
    public object StrBirthDate { get; set; }
    public object Description { get; set; }
    public object JobTitle { get; set; }
    public bool IsLegalSubscriber { get; set; }
    public object SubscriberTypeName { get; set; }
    public int SubscriberTypeId { get; set; }
    public string CityName { get; set; }
    public string DealerId { get; set; }
    public string BranchId { get; set; }
    public string Color { get; set; }
    public string GearBoxType { get; set; }
    public object ManagerName { get; set; }
    public bool PreventRegisterReceptions { get; set; }
    public bool PreventRegisterSpOrderings { get; set; }
    public bool PreventRegisterSPExchanges { get; set; }
    public bool IsLegal { get; set; }
    public object BirthCityId { get; set; }
    public object BirthCityName { get; set; }
    public object IssueCityId { get; set; }
    public object IssueCityName { get; set; }
    public object IssueDate { get; set; }
    public object StrIssueDate { get; set; }
    public object RegisterCityId { get; set; }
    public object RegisterCityName { get; set; }
    public int IsUsedCar { get; set; }
    public string EconomicCode { get; set; }
    public object ContactSubscriberName { get; set; }
    public object ContactSubscriberNationalCode { get; set; }
    public object ContactSubscriberTel { get; set; }
    public object ContactSubscriberMobile { get; set; }
    public object ContactSubscriberBirthCityLocalizedName { get; set; }
    public object ContactSubscriberIdNumber { get; set; }
    public object Email { get; set; }
    public object SignatoryPersons { get; set; }
    public object RealEconomicCode { get; set; }
    public string strIsCompanymortgage { get; set; }
    public object EstablishmentDate { get; set; }
    public object OfficialNewspaperDate { get; set; }
    public object IsLegalSubscriberName { get; set; }
    public object ShareCount { get; set; }
    public string StrShareCount { get; set; }
    public string BriefAddress { get; set; }
    public object TradingSystemRoleCode { get; set; }
    public string subscriberNationalCode { get; set; }
    public string subscriberNationalId { get; set; }
    public string DetailedCode { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class WarrantyOfSevenResponse
{
    public string ReceptionVehicleStatusReceptionId { get; set; }
    public bool ReceptionVehicleStatusIsWarranty { get; set; }
    public string ReceptionVehicleStatusVinNumber { get; set; }
    public string ReceptionVehicleStatusVehicleModel { get; set; }
    public string ReceptionVehicleStatusVehicleModelId { get; set; }
    public string ReceptionVehicleStatusVehicleTypeId { get; set; }
    public DateTime ReceptionVehicleStatusRegisterGuarantyDate { get; set; }
    public string StrReceptionVehicleStatusRegisterGuarantyDate { get; set; }
    public DateTime ReceptionVehicleStatusExpireGuarantyDate { get; set; }
    public string StrReceptionVehicleStatusExpireGuarantyDate { get; set; }
    public int ReceptionVehicleStatusGuarantyDuration { get; set; }
    public int ReceptionVehicleStatusGuarantyMileage { get; set; }
    public object ReceptionVehicleStatusGuarantyClock { get; set; }
    public object ReceptionDashboardSymbolList { get; set; }
    public object StrReceptionDashboardSymbol { get; set; }
    public object ReceptionDashboardSymbols { get; set; }
    public object ReceptionDashboardSymbolSelectedList { get; set; }
    public object accessoriesList { get; set; }
    public object StrReceptionAccessories { get; set; }
    public object ReceptionAccessories { get; set; }
    public object ReceptionAccessoriesSelectedList { get; set; }
    public int FuelStatusId { get; set; }
    public int BatteryStatusId { get; set; }
    public string ReceptionVehicleStatusGearBox { get; set; }
    public string ReceptionVehicleStatusFuelSystem { get; set; }
    public string ReceptionVehicleStatusVehicleColor { get; set; }
    public bool ScratchesAreInvisibleBeacauseOfBeDirty { get; set; }
    public bool AllowVehicleTechnicalTestingInOutService { get; set; }
    public string ReceptionVehicleModel { get; set; }
    public object OriginalRegisterDateTime { get; set; }
    public string ReceptionVehicleStatusGuarantyType { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class DealerOfSevenResponse
{
    public string UniqueId { get; set; }
    public int Code { get; set; }
    public string BranchId { get; set; }
    public string BranchName { get; set; }
    public string BranchNameWithoutDealerName { get; set; }
    public string BranchNo { get; set; }
    public object PersonnelCode { get; set; }
    public string DealerCityLocalizedName { get; set; }
    public string DealerSubCountryLocalizedName { get; set; }
    public string DealerEconomicCode { get; set; }
    public string CentralDealerEconomicCode { get; set; }
    public object ManagerMobile { get; set; }
    public object ManagerPhone { get; set; }
    public object ManagerFax { get; set; }
    public object ManagerEmail { get; set; }
    public object ManagerAddress { get; set; }
    public object RepairShopMobileNumber { get; set; }
    public object RepairShopPhoneNumber { get; set; }
    public object RepairShopFax { get; set; }
    public object RepairShopEmail { get; set; }
    public object RepairShopAddress { get; set; }
    public object RepairShopPostalCode { get; set; }
    public string RegistrationNumber { get; set; }
    public object ExhibitionMobileNumber { get; set; }
    public object ExhibitionPhoneNumber { get; set; }
    public object ExhibitionFax { get; set; }
    public object ExhibitionEmail { get; set; }
    public object ExhibitionAddress { get; set; }
    public object ExhibitionPostalCode { get; set; }
    public object IsqiPersonName { get; set; }
    public string DealerGrade { get; set; }
    public string NationalId { get; set; }
    public string DealerNo { get; set; }
    public string DealerName { get; set; }
    public object PersonnelLocalizedName { get; set; }
    public string ManagerName { get; set; }
    public string BranchManagerName { get; set; }
    public object ManagerDescription { get; set; }
    public bool IsCentralBranch { get; set; }
    public bool IsCentralDealer { get; set; }
    public string Branch_Name { get; set; }
    public object TradingSystemRoleCode { get; set; }
    public string DealerNationalCode { get; set; }
    public string EconomicCodeFroBranch { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class ReceptionOfSevenResponse
{
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public int DealerSystemCode { get; set; }
    public string ReceptionCode { get; set; }
    public object RelatedCode { get; set; }
    public object RelatedName { get; set; }
    public int ReceptionBranchDailyCode { get; set; }
    public int BranchSystemCode { get; set; }
    public float Deposit { get; set; }
    public string SubscriberChassisAllocationId { get; set; }
    public string SubscriberId { get; set; }
    public object VehicleModelId { get; set; }
    public object UserAssignmentId { get; set; }
    public object ChassisInfoId { get; set; }
    public object ChassisUsageTypeLocalizedName { get; set; }
    public string SubscriberLogId { get; set; }
    public string SubscriberName { get; set; }
    public object SubscriberFullName { get; set; }
    public object WorkTell { get; set; }
    public object WorkRoomAddress { get; set; }
    public string SubscriberChassisNo { get; set; }
    public object ParticipationCode { get; set; }
    public object OriginalVinNumber { get; set; }
    public object ChassisPlate { get; set; }
    public string SubscriberPelakNo { get; set; }
    public bool SubscriberWithoutPlate { get; set; }
    public string SubscriberMotorNo { get; set; }
    public string SubscriberVehicleModel { get; set; }
    public string SubscriberVehicleColor { get; set; }
    public bool SubscriberIsLegal { get; set; }
    public string SubscriberNationalCodeOrNationalId { get; set; }
    public string DealerId { get; set; }
    public object ReferenceDealerId { get; set; }
    public object ReferenceDealerName { get; set; }
    public object ReferenceBranchName { get; set; }
    public object ReferenceBranchId { get; set; }
    public string DealerNo { get; set; }
    public string DealerName { get; set; }
    public object BranchName { get; set; }
    public string BranchId { get; set; }
    public string BranchEditLogId { get; set; }
    public string BranchNo { get; set; }
    public DateTime RecDate { get; set; }
    public string StrRecDate { get; set; }
    public string StrRecTime { get; set; }
    public int RecKilometer { get; set; }
    public int RecClock { get; set; }
    public object Description { get; set; }
    public string RepairAdviserId { get; set; }
    public string RepairAdviserName { get; set; }
    public string CashierId { get; set; }
    public string CashierName { get; set; }
    public bool QcFlag { get; set; }
    public string CustomerName { get; set; }
    public object InternalIdentificationNumber { get; set; }
    public string CustomerMobile { get; set; }
    public object CustomerEmail { get; set; }
    public string CustomerNationalCode { get; set; }
    public string CustomerAddress { get; set; }
    public object StrEstimatedDaysToDeliver { get; set; }
    public object TotalWarrantyAmount { get; set; }
    public float EstimatedAmount { get; set; }
    public DateTime EstimatedDeliver { get; set; }
    public string StrEstimatedDeliverDate { get; set; }
    public string StrEstimatedDeliverTime { get; set; }
    public object FirstCreatedUserEstimatedDeliver { get; set; }
    public object FirstCreatedEstimatedDeliverDate { get; set; }
    public object StrFirstCreatedEstimatedDeliverDate { get; set; }
    public object StrFirstCreatedEstimatedDeliverTime { get; set; }
    public object ReliefReceptionId { get; set; }
    public string ReliefReceptionDealerSystemCode { get; set; }
    public object CarwashStartDate { get; set; }
    public string StrCarwashStartDate { get; set; }
    public object CarwashStartTime { get; set; }
    public object CarwashEndDate { get; set; }
    public string StrCarwashEndDate { get; set; }
    public object CarwashEndTime { get; set; }
    public object DeliveryDate { get; set; }
    public string StrDeliveryDate { get; set; }
    public string StrDeliveryTime { get; set; }
    public int DeliveryKilometer { get; set; }
    public int DeliveryClock { get; set; }
    public bool CheckForOwnerPart { get; set; }
    public bool CheckForOwnerStatements { get; set; }
    public int DealerCollectiveInvoiceNumber { get; set; }
    public int BranchCollectiveInvoiceNumber { get; set; }
    public int DealerCollectiveInvoiceNumberByYear { get; set; }
    public int BranchCollectiveInvoiceNumberByYear { get; set; }
    public int DealerInvoiceNumber { get; set; }
    public int BranchInvoiceNumber { get; set; }
    public DateTime InvoiceDate { get; set; }
    public string StrInvoiceDate { get; set; }
    public string StrInvoiceTime { get; set; }
    public int DealerPreInvoiceNumber { get; set; }
    public int BranchPreInvoiceNumber { get; set; }
    public DateTime PreInvoiceDate { get; set; }
    public string StrPreInvoiceDate { get; set; }
    public string StrPreInvoiceTime { get; set; }
    public int FuelStatusId { get; set; }
    public int BatteryStatusId { get; set; }
    public string FuelStatusLocalizedName { get; set; }
    public string BatteryStatusLocalizedName { get; set; }
    public float TotalAmount { get; set; }
    public float DiscountValue { get; set; }
    public float DiscountFee { get; set; }
    public float DiscountPercent { get; set; }
    public float Tax { get; set; }
    public object InServicesTax { get; set; }
    public object OutServicesTax { get; set; }
    public object PartsTax { get; set; }
    public float Toll { get; set; }
    public object InServicesToll { get; set; }
    public object OutServicesToll { get; set; }
    public object PartsToll { get; set; }
    public float EndAmount { get; set; }
    public float ParkingAmount { get; set; }
    public int ParkingDay { get; set; }
    public float StopPenaltyAmount { get; set; }
    public bool FinalPayment { get; set; }
    public bool Cancellation { get; set; }
    public bool Invoiced { get; set; }
    public object FiscalYearId { get; set; }
    public object FiscalYear { get; set; }
    public int PrintCountPreInvoice { get; set; }
    public int PrintCountInvoice { get; set; }
    public int PrintCountRepairCard { get; set; }
    public int ReceptionStateOrderId { get; set; }
    public string ReceptionStateOrder { get; set; }
    public string RowVersion { get; set; }
    public string ReceptionType { get; set; }
    public object KilometerModificationDescription { get; set; }
    public object ReceptionStatus { get; set; }
    public object DealerBranchNo { get; set; }
    public string VehicleFullName { get; set; }
    public object WarrantyStatus { get; set; }
    public object LastDraftResultCode { get; set; }
    public float PartAmount { get; set; }
    public float InServiceAmount { get; set; }
    public float OutServiceAmount { get; set; }
    public string ReceptionControlDescription { get; set; }
    public object ReceptionControlDate { get; set; }
    public object StrReceptionControlDate { get; set; }
    public object StrReceptionControlTime { get; set; }
    public object WareHouseId { get; set; }
    public string ReceptionVehicleStatusGearBox { get; set; }
    public object OnlinePersonnel { get; set; }
    public object ReceptionCount { get; set; }
    public object QualityControlStartDate { get; set; }
    public string StrQualityControlStartDate { get; set; }
    public string StrQualityControlStartTime { get; set; }
    public object QualityControlEndDate { get; set; }
    public string StrQualityControlEndDate { get; set; }
    public string StrQualityControlEndTime { get; set; }
    public string ReceptionVehicleModelName { get; set; }
    public object BookingDate { get; set; }
    public string StrBookingDate { get; set; }
    public object BookingCode { get; set; }
    public object BookingKilometer { get; set; }
    public object ReceptionLicenseBranchSyastemCode { get; set; }
    public object[] ReceptionAccessoriesList { get; set; }
    public object[] ReceptionControlList { get; set; }
    public object[] ReceptionCustomerStatementsList { get; set; }
    public object[] ReceptionDashboardSymbolList { get; set; }
    public object[] ReceptionEstimatedList { get; set; }
    public object[] ReceptionInServicesList { get; set; }
    public object[] ReceptionOutServicesList { get; set; }
    public object[] ReceptionPartsOrderList { get; set; }
    public object[] ReceptionPartsList { get; set; }
    public object[] ReceptionPositionList { get; set; }
    public object[] ReceptionQualityControlList { get; set; }
    public object[] ReceptionRoadTestList { get; set; }
    public object[] ReceptionSuspensionList { get; set; }
    public object[] ReceptionTypeList { get; set; }
    public object[] ReceptionWorkShopContractList { get; set; }
    public object AreaCategoryId { get; set; }
    public object ReceptionTaskApproveDescription { get; set; }
    public object ReceptionTaskApprovedUserId { get; set; }
    public string ReceptionTaskApprovedUser { get; set; }
    public object ReceptionTaskApprovedDate { get; set; }
    public object StrReceptionTaskApprovedDate { get; set; }
    public string ReceptionCustomerSignatureId { get; set; }
    public object ReceptionFinancialCustomerSignatureId { get; set; }
    public object RepairHall { get; set; }
    public object ServerGroup { get; set; }
    public object ReceptionTimeInterval { get; set; }
    public object ChassisGuaranteeRegisterDate { get; set; }
    public object StrChassisGuaranteeRegisterDate { get; set; }
    public object BrandName { get; set; }
    public object DealerEconomicCode { get; set; }
    public object DealerPostalCode { get; set; }
    public object DealerAddress { get; set; }
    public object DealerPhone { get; set; }
    public object[] ReceptionTypes { get; set; }
    public string StrReceptionTypes { get; set; }
    public int ReceptionListLastKilometer { get; set; }
    public object ReceptionInvoiceUrl { get; set; }
    public object ReceptionRepairCardUrl { get; set; }
    public object ReceptionStatusPreviewUrl { get; set; }
    public object ServiceId { get; set; }
    public object ServiceCode { get; set; }
    public object PartId { get; set; }
    public object PartNo { get; set; }
    public object PartSerial { get; set; }
    public object OldProviderName { get; set; }
    public object OldPartName { get; set; }
    public bool SendDocumentsOfBuyTransactions { get; set; }
    public int ReceptionControlCount { get; set; }
    public string VehicleTypeLocalizedName { get; set; }
    public string BrandLocalizedName { get; set; }
    public object WarehouseLocalizedName { get; set; }
    public string VehicleTypeVehicleName { get; set; }
    public string ProductYear { get; set; }
    public int DealerCode { get; set; }
    public object WeekDayStartAndEndTime { get; set; }
    public object ThursdayStartAndEndTime { get; set; }
    public object HolidayStartAndEndTime { get; set; }
    public object CurrentDay { get; set; }
    public object AbreviatedName { get; set; }
    public float AccountingOnlineCredit { get; set; }
    public object OnlineCredit { get; set; }
    public object Credit { get; set; }
    public object ProductionDate { get; set; }
    public string StrProductionDate { get; set; }
    public object VehicleTypeName { get; set; }
    public object VehicleSaleDeliveryDate { get; set; }
    public string StrVehicleSaleDeliveryDate { get; set; }
    public object IncludesTax { get; set; }
    public bool ReceptionListIsClaimAccountSettlement { get; set; }
    public string ReceptionVehicleAbreviatedName { get; set; }
    public bool ReceptionListActiveClaimAccountSettlement { get; set; }
    public object ReceptionListClaimAccountSettlement { get; set; }
    public bool DeliverFailurePartToCustomer { get; set; }
    public object VehicleTypeId { get; set; }
    public string ReceptionListBranchGrade { get; set; }
    public object NoticeDescription { get; set; }
    public string ReceptionVehicleName { get; set; }
    public object SubscriberTel { get; set; }
    public bool IsDelivered { get; set; }
    public object SubscriberBodyNumber { get; set; }
    public int Gender { get; set; }
    public string EstimatedDeliverTime { get; set; }
    public object ReceptionCustomerSignature { get; set; }
    public bool ReceptionEstimatedHasCustomersSignature { get; set; }
    public object NationalCodOrNationalId { get; set; }
    public object EconomicCode { get; set; }
    public object GuarantyTypeInReception { get; set; }
    public bool ReceptionByReceptionApp { get; set; }
    public int TotalCount { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class ReportdetailOfSevenResponse
{
    public string CompanyName { get; set; }
    public object ManagerName { get; set; }
    public DateTime PrintDate { get; set; }
    public string StrPrintDate { get; set; }
    public string StrPrintTime { get; set; }
    public object PrintPersonnelName { get; set; }
    public object DocumentName { get; set; }
    public object DocumentNumber { get; set; }
    public string PayableAmountToLetters { get; set; }
    public float PayableAmount { get; set; }
    public object DealerName { get; set; }
    public object BranchName { get; set; }
    public object StartDate { get; set; }
    public object StrStartDate { get; set; }
    public object StrStartTime { get; set; }
    public object EndDate { get; set; }
    public object StrEndDate { get; set; }
    public object StrEndTime { get; set; }
    public object ReceptionControlDescription { get; set; }
    public float PrePayment { get; set; }
    public object RegisterCode { get; set; }
    public object CompanyWebSite { get; set; }
    public int DealerCode { get; set; }
    public object FiscalYear { get; set; }
    public object OnlineSaleUrl { get; set; }
    public object NationCode { get; set; }
    public object Address { get; set; }
    public object Tel { get; set; }
    public object Fax { get; set; }
    public object PostalCode { get; set; }
    public object TotalWarrantyWithTax { get; set; }
}

public class SignaturemodelOfSevenResponse
{
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public int ReportId { get; set; }
    public object Report { get; set; }
    public object FirstSignatoryTitle { get; set; }
    public object FirstSignatoryPersonnelId { get; set; }
    public object FirstSignatoryPersonnel { get; set; }
    public object SecondSignatoryTitle { get; set; }
    public object SecondSignatoryPersonnelId { get; set; }
    public object SecondSignatoryPersonnel { get; set; }
    public object ThirdSignatoryTitle { get; set; }
    public object ThirdSignatoryPersonnelId { get; set; }
    public object ThirdSignatoryPersonnel { get; set; }
    public object DealerId { get; set; }
    public object DealerName { get; set; }
    public object DealerNo { get; set; }
    public object BranchId { get; set; }
    public object BranchName { get; set; }
    public object BranchNo { get; set; }
    public object Description { get; set; }
    public string FirstSignatureUrl { get; set; }
    public string SecondSignatureUrl { get; set; }
    public string ThirdSignatureUrl { get; set; }
    public object SignatureCustomerUrl { get; set; }
    public object AreaCategoryId { get; set; }
    public object AreaCategoryName { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}

public class TextofprinteddetailOfSevenResponse
{
    public string UniqueId { get; set; }
    public int Code { get; set; }
    public object ReceptionFactorDescription { get; set; }
    public object SecondReceptionFactorDescription { get; set; }
    public object ThirdReceptionFactorDescription { get; set; }
    public object ClaimFactorDescription { get; set; }
    public object ClaimDebtExitFactorDescription { get; set; }
    public object PartSaleFactorDescription { get; set; }
    public object ReturnFromInvoiceFactorDescription { get; set; }
    public object SatisfactionFactorDescription { get; set; }
    public object RepairCardDescription { get; set; }
    public object VeicleSaleDescription { get; set; }
    public object ReliefDescription { get; set; }
    public object WorkShopContractDescription { get; set; }
    public object GuarantySaleDescription { get; set; }
    public object DeliveryReceiptDescription { get; set; }
    public object RepairHallCardDescription { get; set; }
}

public class PartandservicelistOfSevenResponse
{
    public string UniqueId { get; set; }
    public string ReceptionId { get; set; }
    public string Type { get; set; }
    public string ServiceCodeOrPartNo { get; set; }
    public object PartNumber { get; set; }
    public string ServiceCodeOrOldPartNo { get; set; }
    public string ServiceOrPartName { get; set; }
    public object ServiceOrPartLocalizedName { get; set; }
    public object ServiceOrPartEnglishName { get; set; }
    public float Number { get; set; }
    public string Unit { get; set; }
    public float UnitPrice { get; set; }
    public float TotalAmount { get; set; }
    public float Discount { get; set; }
    public float TotalAmountAfterDiscount { get; set; }
    public float Taxes { get; set; }
    public float Tax { get; set; }
    public float Toll { get; set; }
    public float EndAmount { get; set; }
    public string CostCenterLocalizedName { get; set; }
    public object Description { get; set; }
    public object PartSerialNo { get; set; }
    public float ServiceTime { get; set; }
    public object BrandLocalizedName { get; set; }
    public object PartProviderLocalizedCode { get; set; }
    public object PartProviderLocalizedName { get; set; }
    public string OldPartNo { get; set; }
}

public class PartandservicelistbycostcenterOfSevenResponse
{
    public string UniqueId { get; set; }
    public string CostCenterId { get; set; }
    public int CostCenterEnumCode { get; set; }
    public string CostCenterLocalizedName { get; set; }
    public bool IsPayableForCustomer { get; set; }
    public bool IsInService { get; set; }
    public bool IsOutService { get; set; }
    public bool IsPart { get; set; }
    public bool IsItemType { get; set; }
    public float TotalAmount { get; set; }
    public float Discount { get; set; }
    public float Tax { get; set; }
    public float Toll { get; set; }
    public float TaxGuaranty { get; set; }
    public float TollGuaranty { get; set; }
    public float EndAmount { get; set; }
    public float TotalEndAmount { get; set; }
    public float SumTime { get; set; }
    public string ReceptionFinancialType { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}
