namespace NamiCustomers.Infrastucture.ExternalServices.SevenSoft.Dtos;

public class SpOrderingsBySubscriberResponse
{
    public string TrackCode => $"{DealerNo}-{BranchNo}-{DealerSystemCode}";
    public int Code { get; set; }
    public string UniqueId { get; set; }
    public int DealerSystemCode { get; set; }
    public int BranchSystemCode { get; set; }
    public string DealerId { get; set; }
    public string DealerNo { get; set; }
    public object DealerName { get; set; }
    public string BranchId { get; set; }
    public string BranchNo { get; set; }
    public object BranchName { get; set; }
    public object SporderingCode { get; set; }
    public string SubscriberChassisAllocationId { get; set; }
    public object SubscriberId { get; set; }
    public string SubscriberName { get; set; }
    public object SubscriberNameWithoutNationalCode { get; set; }
    public object SubscriberMobile { get; set; }
    public object ChassisPlate { get; set; }
    public object ReceptionId { get; set; }
    public object ReceptionCode { get; set; }
    public object WarrantyStatus { get; set; }
    public int ReceptionDealerSystemCode { get; set; }
    public string RegisterPersonnelId { get; set; }
    public string PersonnelName { get; set; }
    public int OrderTypeId { get; set; }
    public string OrderTypeLocalizedName { get; set; }
    public string RelatedSystemCode { get; set; }
    public string OrderPriorityTypeId { get; set; }
    public string OrderPriorityTypeLocalizedName { get; set; }
    public object OrderReceiveTypeId { get; set; }
    public string OrderReceiveTypeLocalizedName { get; set; }
    public object OrderStatusTypeId { get; set; }
    public string OrderStatusTypeLocalizedName { get; set; }
    public string PaymentTypeId { get; set; }
    public string PaymentTypeLocalizedName { get; set; }
    public string DestinationDealerId { get; set; }
    public string DestinationBranchId { get; set; }
    public bool IsBackOrder { get; set; }
    public bool Sent { get; set; }
    public DateTime SentDate { get; set; }
    public string StrSentDate { get; set; }
    public string StrSentTime { get; set; }
    public bool Status { get; set; }
    public string StatusDescription { get; set; }
    public float TotalFee { get; set; }
    public float Discount { get; set; }
    public float DiscountPercent { get; set; }
    public float Tax { get; set; }
    public float Toll { get; set; }
    public float EndFee { get; set; }
    public object[] SpOrderingParts { get; set; }
    public DateTime Date { get; set; }
    public string StrDate { get; set; }
    public string StrTime { get; set; }
    public string SpExchangeId { get; set; }
    public string SpOrderingSourceWareHouseId { get; set; }
    public string SpOrderingSourceWareHouse { get; set; }
    public string VinNumber { get; set; }
    public object PartNo { get; set; }
    public object PartLocalizedName { get; set; }
    public object CustomerMobile { get; set; }
    public object CustomerEmail { get; set; }
    public string ChassisNo { get; set; }
    public object PartConsumptionTypeId { get; set; }
    public object PartConsumptionTypeName { get; set; }
    public object CargoVehicleTypeId { get; set; }
    public object CargoVehicleTypeName { get; set; }
    public object SpExchangesDealerFactorCode { get; set; }
    public object SpExchangesDealerYearFactorCode { get; set; }
    public object SpExchangesBranchFactorCode { get; set; }
    public object SpExchangesBranchYearFactorCode { get; set; }
    public object SpExchangesBranchCollectiveInvoiceNumberByYear { get; set; }
    public object SpExchangesDealerCollectiveInvoiceNumber { get; set; }
    public object SpOrderingListVmSpecialSubscriberGroupName { get; set; }
    public object SpOrderingListVmCityName { get; set; }
    public object SpOrderingListVmVehicleModelName { get; set; }
    public object SpOrderingListVmReceiptionStateOrder { get; set; }
    public object SpOrderingListVmReceptionRecKilometer { get; set; }
    public object SpOrderingListVmTechnicianName { get; set; }
    public object SpOrderingListVmDescription { get; set; }
    public object PartTypeId { get; set; }
    public object PartType { get; set; }
    public object PartName { get; set; }
    public object CountingUnitLocalizedName { get; set; }
    public float UnitPrice { get; set; }
    public int Number { get; set; }
    public object TemporaryReceiptDealerNo { get; set; }
    public int TemporaryReceiptDealerSystemCode { get; set; }
    public object SpexchangesStateOrderId { get; set; }
    public object State { get; set; }
    public int Gender { get; set; }
    public string ClientId { get; set; }
    public bool IsDirty { get; set; }
}
