<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <NoWarn>$(NoWarn);NU1903</NoWarn>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>04.08.27.1</AssemblyVersion>
    <FileVersion>04.08.27.1</FileVersion>
    <Version>04.08.27.1</Version>
    <InformationalVersion>04.08.27.1 - 2025-11-18</InformationalVersion>
    <AssemblyDescription>Alimoradi573@gmail.com</AssemblyDescription>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FakesAssemblies\**" />
    <EmbeddedResource Remove="FakesAssemblies\**" />
    <None Remove="FakesAssemblies\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="EfCore.SchemaCompare" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.11" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
    <PackageReference Include="Microsoft.QualityTools.Testing.Fakes" Version="18.1.1" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalDesignTimeBuildInput Remove="FakesAssemblies\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NamiCustomers.Abstractions\NamiCustomers.Abstractions.csproj" />
    <ProjectReference Include="..\NamiCustomers.Domain\NamiCustomers.Domain.csproj" />
    <ProjectReference Include="..\NamiCustomers.Infrastucture\NamiCustomers.Infrastucture.csproj" />
  </ItemGroup>
</Project>