<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>04.08.27.1</AssemblyVersion>
    <FileVersion>04.08.27.1</FileVersion>
    <Version>04.08.27.1</Version>
    <InformationalVersion>04.08.27.1 - 2025-11-18</InformationalVersion>
    <AssemblyDescription>Alimoradi573@gmail.com</AssemblyDescription>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="CodeTemplates\**" />
    <EmbeddedResource Remove="CodeTemplates\**" />
    <None Remove="CodeTemplates\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.9" />
  </ItemGroup>
</Project>