global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Moq;
global using NamiCustomers.Application.DTOs;
global using NamiCustomers.Application.Services;
global using Xunit;
global using Xunit.Abstractions;
global using NamiCustomers.API;