//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamiCustomers.Infrastucture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamiCustomers.Infrastucture.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر امکان استعلام از سامانه فاوا وجود ندارد.
        /// </summary>
        public static string errCannotGetFavaDatas {
            get {
                return ResourceManager.GetString("errCannotGetFavaDatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف نشد.
        /// </summary>
        public static string errDelete {
            get {
                return ResourceManager.GetString("errDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلا این شماره شاسی برای مشترک ثبت شده است.
        /// </summary>
        public static string errDuplicateSubscriberVin {
            get {
                return ResourceManager.GetString("errDuplicateSubscriberVin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نشد.
        /// </summary>
        public static string errEdited {
            get {
                return ResourceManager.GetString("errEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان پایان نمی تواند قبل یا برابر زمان آغاز باشد.
        /// </summary>
        public static string errEndTimeCannotEqualOrLessThanStatrtTime {
            get {
                return ResourceManager.GetString("errEndTimeCannotEqualOrLessThanStatrtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شاسی به نام مشترک دیگری ثبت شده است.
        /// </summary>
        public static string errExistedSubscriber {
            get {
                return ResourceManager.GetString("errExistedSubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام درخواست امکان پذیر نیست.
        /// </summary>
        public static string errFailed {
            get {
                return ResourceManager.GetString("errFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کد ملی وارد شده قرارداد فعال از قبل در سامانه فاوا موجود می باشد.
        /// </summary>
        public static string errFavaNationalCodeExisted {
            get {
                return ResourceManager.GetString("errFavaNationalCodeExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل باید حداکثر }0{MBباشد.
        /// </summary>
        public static string errFileSize {
            get {
                return ResourceManager.GetString("errFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا دریافت کد تایید.
        /// </summary>
        public static string errGetOtp {
            get {
                return ResourceManager.GetString("errGetOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنها می توان تصاویر از نوع 
        /// را بارگزاری نمودPNG,JPG,JPEG.
        /// </summary>
        public static string errImageExtentions {
            get {
                return ResourceManager.GetString("errImageExtentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ورودی معتبر نمی باشد.
        /// </summary>
        public static string errInputInValid {
            get {
                return ResourceManager.GetString("errInputInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده معتبر نیست.
        /// </summary>
        public static string errInvalidMobile {
            get {
                return ResourceManager.GetString("errInvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی معتبر نمی باشد.
        /// </summary>
        public static string errInvalidNationalCode {
            get {
                return ResourceManager.GetString("errInvalidNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید وارد شده اشتباه است.
        /// </summary>
        public static string errMistakeConfirmCode {
            get {
                return ResourceManager.GetString("errMistakeConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده در سامانه ثبت احوال معتبر نمیباشد.
        /// </summary>
        public static string errNationalCodeInvalidInSabtAhval {
            get {
                return ResourceManager.GetString("errNationalCodeInvalidInSabtAhval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده شامل طرح جانبازان نمی باشد.
        /// </summary>
        public static string errNationalCodeNotContainsJAnbazan {
            get {
                return ResourceManager.GetString("errNationalCodeNotContainsJAnbazan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت نشد.
        /// </summary>
        public static string errNotFound {
            get {
                return ResourceManager.GetString("errNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نوبت باید بزرگتر از صفر باشد.
        /// </summary>
        public static string errNumberOfAppointmentsCanNotEqualOrLessThanZero {
            get {
                return ResourceManager.GetString("errNumberOfAppointmentsCanNotEqualOrLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نمی باشد.
        /// </summary>
        public static string errOtpInvalid {
            get {
                return ResourceManager.GetString("errOtpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسال شده را وارد نمایید..
        /// </summary>
        public static string errOtpIsNotNull {
            get {
                return ResourceManager.GetString("errOtpIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا ذخیره.
        /// </summary>
        public static string errSave {
            get {
                return ResourceManager.GetString("errSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بانک را انتخاب کنید.
        /// </summary>
        public static string errSelectBank {
            get {
                return ResourceManager.GetString("errSelectBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی در ارسال پیامک رخ داده است.
        /// </summary>
        public static string errSmsPanelHasError {
            get {
                return ResourceManager.GetString("errSmsPanelHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشترک مورد نظر یافت نشد.
        /// </summary>
        public static string errSubscriberNotFound {
            get {
                return ResourceManager.GetString("errSubscriberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزهای پنجشنبه وجمعه تعطیل است.
        /// </summary>
        public static string errVacationDateNotSelectable {
            get {
                return ResourceManager.GetString("errVacationDateNotSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو11.
        /// </summary>
        public static string msgCancel {
            get {
                return ResourceManager.GetString("msgCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شد.
        /// </summary>
        public static string msgDeleted {
            get {
                return ResourceManager.GetString("msgDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروجی با موفقیت دانلود شد.
        /// </summary>
        public static string msgDownloadSuccess {
            get {
                return ResourceManager.GetString("msgDownloadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش شد.
        /// </summary>
        public static string msgEdited {
            get {
                return ResourceManager.GetString("msgEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید را وارد نمایید.
        /// </summary>
        public static string msgEnterConfirmCode {
            get {
                return ResourceManager.GetString("msgEnterConfirmCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی و موبایل را وارد نمایید.
        /// </summary>
        public static string msgEnterNationalCode_Mobile {
            get {
                return ResourceManager.GetString("msgEnterNationalCode&Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سامانه با موفقیت انجام شد.
        /// </summary>
        public static string msgEnterSuccess {
            get {
                return ResourceManager.GetString("msgEnterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت شد.
        /// </summary>
        public static string msgFound {
            get {
                return ResourceManager.GetString("msgFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ رکوردی وجود ندارد.
        /// </summary>
        public static string msgNotFoundAnyResult {
            get {
                return ResourceManager.GetString("msgNotFoundAnyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیتا با موفقیت بازگشت داده شد.
        /// </summary>
        public static string msgReturnDataSuccess {
            get {
                return ResourceManager.GetString("msgReturnDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره شد.
        /// </summary>
        public static string msgSave {
            get {
                return ResourceManager.GetString("msgSave", resourceCulture);
            }
        }
    }
}
