//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamiCustomers.Infrastucture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource7Soft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource7Soft() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamiCustomers.Infrastucture.Properties.Resource7Soft", typeof(Resource7Soft).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://172.20.10.6:8087/.
        /// </summary>
        public static string BaseUrlBooking {
            get {
                return ResourceManager.GetString("BaseUrlBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://172.20.10.6:8088/.
        /// </summary>
        public static string BaseUrlCrm {
            get {
                return ResourceManager.GetString("BaseUrlCrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://172.20.10.6:8089/.
        /// </summary>
        public static string BaseUrlSales {
            get {
                return ResourceManager.GetString("BaseUrlSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/CancelBooking?BookingId={0}&amp;VinNumber={1}.
        /// </summary>
        public static string CancelBooking {
            get {
                return ResourceManager.GetString("CancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/CheckExistsReserveVinNumber.
        /// </summary>
        public static string CheckExistsReserveVinNumber {
            get {
                return ResourceManager.GetString("CheckExistsReserveVinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/CheckIsValidKilometer.
        /// </summary>
        public static string CheckIsValidKilometer {
            get {
                return ResourceManager.GetString("CheckIsValidKilometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Guaranty/GetActiveMainChassisGuarantee?vinNumber=.
        /// </summary>
        public static string GetActiveMainChassisGuarantee {
            get {
                return ResourceManager.GetString("GetActiveMainChassisGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getAllBranch.
        /// </summary>
        public static string GetAllBranch {
            get {
                return ResourceManager.GetString("GetAllBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/VINInformation/GetAllChassisInformation?NationalCodeOrEconomicCode={0}.
        /// </summary>
        public static string GetAllChassisInformation {
            get {
                return ResourceManager.GetString("GetAllChassisInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getAllCity.
        /// </summary>
        public static string GetAllCity {
            get {
                return ResourceManager.GetString("GetAllCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/GetAllDealer.
        /// </summary>
        public static string GetAllDealer {
            get {
                return ResourceManager.GetString("GetAllDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/SpOrdering/GetAllOrderStatusType.
        /// </summary>
        public static string GetAllOrderStatusTypeResponse {
            get {
                return ResourceManager.GetString("GetAllOrderStatusTypeResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getAllServerGroup.
        /// </summary>
        public static string GetAllServerGroup {
            get {
                return ResourceManager.GetString("GetAllServerGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getAllServerGroupDate.
        /// </summary>
        public static string GetAllServerGroupDate {
            get {
                return ResourceManager.GetString("GetAllServerGroupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getAllServerGroupRepairAdvisers?WorkShopTimeTableId={0}&amp;ServerGroupId={1}.
        /// </summary>
        public static string GetAllServerGroupRepairAdvisers {
            get {
                return ResourceManager.GetString("GetAllServerGroupRepairAdvisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getAllServerGroupTime.
        /// </summary>
        public static string GetAllServerGroupTime {
            get {
                return ResourceManager.GetString("GetAllServerGroupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getAllSubCountries.
        /// </summary>
        public static string GetAllSubCountries {
            get {
                return ResourceManager.GetString("GetAllSubCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/GetBooking?VinNumber={0}.
        /// </summary>
        public static string GetBooking {
            get {
                return ResourceManager.GetString("GetBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Dealer/GetBranchesByDealer?DealerId=.
        /// </summary>
        public static string GetBranchesByDealer {
            get {
                return ResourceManager.GetString("GetBranchesByDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/VINInformation/GetChassisInformationByVinNumber?VinNumber=.
        /// </summary>
        public static string GetChassisInformationByVinNumber {
            get {
                return ResourceManager.GetString("GetChassisInformationByVinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Dealer/GetDealers.
        /// </summary>
        public static string GetDealers {
            get {
                return ResourceManager.GetString("GetDealers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/PartServicePrice/GetPartsPriceByChassis.
        /// </summary>
        public static string GetPartsPriceByChassis {
            get {
                return ResourceManager.GetString("GetPartsPriceByChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ReceptionInformaionHistory/GetReceptionCustomerStatementInformationByReceptionCode.
        /// </summary>
        public static string GetReceptionCustomerStatementInformationByReceptionCode {
            get {
                return ResourceManager.GetString("GetReceptionCustomerStatementInformationByReceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ReceptionInvoiceReport/getReceptionsInformationByReceptionID.
        /// </summary>
        public static string getReceptionsInformationByReceptionID {
            get {
                return ResourceManager.GetString("getReceptionsInformationByReceptionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ReceptionInformaion/GetReceptionsInformationByVinNumber?ChassisVinNumber=.
        /// </summary>
        public static string GetReceptionsInformationByVinNumber {
            get {
                return ResourceManager.GetString("GetReceptionsInformationByVinNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ReceptionInformaionHistory/GetReceptionsInServicesInformationByReceptionCode.
        /// </summary>
        public static string GetReceptionsInServicesInformationByReceptionCode {
            get {
                return ResourceManager.GetString("GetReceptionsInServicesInformationByReceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ReceptionInformaionHistory/GetReceptionsOutServicesInformationByReceptionCode.
        /// </summary>
        public static string GetReceptionsOutServicesInformationByReceptionCode {
            get {
                return ResourceManager.GetString("GetReceptionsOutServicesInformationByReceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/ReceptionInformaionHistory/GetReceptionsPartsInformationByReceptionCode.
        /// </summary>
        public static string GetReceptionsPartsInformationByReceptionCode {
            get {
                return ResourceManager.GetString("GetReceptionsPartsInformationByReceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/PartServicePrice/GetServicesPriceByBranchId.
        /// </summary>
        public static string GetServicesPriceByBranchId {
            get {
                return ResourceManager.GetString("GetServicesPriceByBranchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/VINInformation/GetSpecificCases.
        /// </summary>
        public static string GetSpecificCases {
            get {
                return ResourceManager.GetString("GetSpecificCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/SpOrdering/GetSpOrderingPartSpOrderingCode?SpOrderingCode={0}.
        /// </summary>
        public static string GetSpOrderingPartSpOrderingCode {
            get {
                return ResourceManager.GetString("GetSpOrderingPartSpOrderingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/SpOrdering/GetSpOrderingsBySubscriber?ChassisVinNumber={0}&amp;NationalCodeOrEconomicCode={1}.
        /// </summary>
        public static string GetSpOrderingsBySubscriber {
            get {
                return ResourceManager.GetString("GetSpOrderingsBySubscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Subscriber/GetSubscriberByNationalCode?NationalCode=.
        /// </summary>
        public static string GetSubscriberByNationalCode {
            get {
                return ResourceManager.GetString("GetSubscriberByNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/getSubscriberChassisAllocation.
        /// </summary>
        public static string GetSubscriberChassisAllocation {
            get {
                return ResourceManager.GetString("GetSubscriberChassisAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/Booking/InsertBooking.
        /// </summary>
        public static string InsertBooking {
            get {
                return ResourceManager.GetString("InsertBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/VINInformation/RelationCustomerInfoByVinNumber.
        /// </summary>
        public static string RelationCustomerInfoByVinNumber {
            get {
                return ResourceManager.GetString("RelationCustomerInfoByVinNumber", resourceCulture);
            }
        }
    }
}
