//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamiCustomers.Infrastucture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource7Soft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource7Soft() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamiCustomers.Infrastucture.Properties.Resource7Soft", typeof(Resource7Soft).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7soft.nami.local:8089/api/OnlineSale/AddAccountingForApi.
        /// </summary>
        public static string AddAccountingForApi {
            get {
                return ResourceManager.GetString("AddAccountingForApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7soft.nami.local:8089/api/OnlineSale/AddOrUpdatevehicleSaleAttachment.
        /// </summary>
        public static string AddOrUpdatevehicleSaleAttachment {
            get {
                return ResourceManager.GetString("AddOrUpdatevehicleSaleAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7soft.nami.local:8089/api/OnlineSale/DeletevehicleSaleAttachment.
        /// </summary>
        public static string DeletevehicleSaleAttachment {
            get {
                return ResourceManager.GetString("DeletevehicleSaleAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7soft.nami.local:8089/api/OnlineSale/GetAllRequiredAttachmentRequirements?VehicleSaleId=.
        /// </summary>
        public static string GetAllRequiredAttachmentRequirements {
            get {
                return ResourceManager.GetString("GetAllRequiredAttachmentRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7soft.nami.local:8089/api/OnlineSale/GetAllVehicleModel?SubscriberId=.
        /// </summary>
        public static string GetAllVehicleModel {
            get {
                return ResourceManager.GetString("GetAllVehicleModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7soft.nami.local:8089/api/Subscriber/GetSubscriberByNationalCode?NationalCode=.
        /// </summary>
        public static string GetSubscriberByNationalCode {
            get {
                return ResourceManager.GetString("GetSubscriberByNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://7soft.nami.local:8089/api/OnlineSale/InsertOnlineSale.
        /// </summary>
        public static string InsertOnlineSale {
            get {
                return ResourceManager.GetString("InsertOnlineSale", resourceCulture);
            }
        }
    }
}
