//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamiCustomers.Infrastucture.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceIranFava {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceIranFava() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NamiCustomers.Infrastucture.Properties.ResourceIranFava", typeof(ResourceIranFava).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://jservice.saleauto.ir/api/services/app/BlackList/.
        /// </summary>
        public static string BlackList {
            get {
                return ResourceManager.GetString("BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://namisign.iranfab.com/api/services/app/SignService/CreateSign.
        /// </summary>
        public static string CreateSign {
            get {
                return ResourceManager.GetString("CreateSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل ثبت شده با موبایل اعلام شده توسط سامانه مغایرت دارد..
        /// </summary>
        public static string errMobileNotEqual {
            get {
                return ResourceManager.GetString("errMobileNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی ثبت شده با کد ملی اعلام شده توسط سامانه مغایرت دارد.
        /// </summary>
        public static string errNationalCodeNotEqual {
            get {
                return ResourceManager.GetString("errNationalCodeNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با پارامترهای وارد شده اطلاعات از قبل وجود دارد.
        /// </summary>
        public static string errPreviousDataExisted {
            get {
                return ResourceManager.GetString("errPreviousDataExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در خواندن اطلاعات از سرویس فاوا.
        /// </summary>
        public static string errReadDataService {
            get {
                return ResourceManager.GetString("errReadDataService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.saleauto.ir/api/services/app/Company/GetCustomersAndCars.
        /// </summary>
        public static string GetCustomersAndCarsUrl {
            get {
                return ResourceManager.GetString("GetCustomersAndCarsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://namisign.iranfab.com/api/services/app/SignService/InquirySign?workflowTicket=.
        /// </summary>
        public static string InquirySign {
            get {
                return ResourceManager.GetString("InquirySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://jservice.saleauto.ir/api/TokenAuth/Auth/.
        /// </summary>
        public static string TokenAuth {
            get {
                return ResourceManager.GetString("TokenAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://service.saleauto.ir/api/TokenAuth/Auth/Auth.
        /// </summary>
        public static string tokenUrl {
            get {
                return ResourceManager.GetString("tokenUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_NAMKHOD.
        /// </summary>
        public static string userID {
            get {
                return ResourceManager.GetString("userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gtfWRY#@$%m.
        /// </summary>
        public static string userPWD {
            get {
                return ResourceManager.GetString("userPWD", resourceCulture);
            }
        }
    }
}
